language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"

before_install:
  - npm update -g npm

notifications:
  email:
    recipients:
      - martin@pipedrive.com
    on_success: change
    on_failure: change

script: "npm run-script test-travis"

sudo: false
